/*
 * ConexionURL.java
 *
 * Created on 23-feb-2011, 0:38:26
 */

package url;

import java.net.*;
import java.io.*;

/**
 * Este ejemplo muestra el uso de la clase URL para conectarse a un servidor,
 * enviar una petición (opcionalmente con parámetros) y recibir la respuesta
 * @author jose
 */
public class ConexionURL extends javax.swing.JFrame {

    private BufferedReader entrada = null;
    private OutputStreamWriter salida = null;
    private URLConnection conexion = null;

    /** Creates new form ConexionURL */
    public ConexionURL() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoURL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        campoEntrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("URL:");

        campoURL.setText("http://www.google.es");
        campoURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoURLurlIntroducida(evt);
            }
        });

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        campoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEntradaurlIntroducida(evt);
            }
        });

        jLabel2.setText("Entrada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(campoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(campoURL, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoURLurlIntroducida(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoURLurlIntroducida
        conectar();
}//GEN-LAST:event_campoURLurlIntroducida

    private void campoEntradaurlIntroducida(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEntradaurlIntroducida
            try {
                // Obtiene una secuencia de salida de caracteres para enviar la peticion
                salida = new OutputStreamWriter(conexion.getOutputStream());
                // Envia la peticion
                salida.write(campoEntrada.getText());
                String linea;
                // Obtiene una secuencia de entrada de caracteres para leer
                // la respuesta
                entrada = new BufferedReader(new InputStreamReader(conexion.getInputStream()));
                // Lee de la secuencia de entrada mientras la conexion siga abierta
                while ((linea = entrada.readLine()) != null)
                        texto.append(linea + "\n");
                entrada.close();
                salida.close();
            } catch (Exception e) {
                System.err.println(e.getMessage());
            }
    }//GEN-LAST:event_campoEntradaurlIntroducida

    public void conectar() {
        try {
            // Realiza la conexion y la configura para poder enviar una peticion
            conexion = (new URL(campoURL.getText())).openConnection();
            conexion.setDoOutput(true);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexionURL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoEntrada;
    private javax.swing.JTextField campoURL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables

}
