/*
 * MostrarHTML.java
 *
 * Created on 22-feb-2011, 23:40:07
 */

package url;

import java.net.*;
import java.io.*;

/**
 * Este ejemplo muestra el uso de la clase URL para mostrar el contenido (en HTML) de la URL especificada
 * @author jose
 */
public class MostrarHTML extends javax.swing.JFrame {

    /** Creates new form MostrarHTML */
    public MostrarHTML() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoURL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("URL:");

        campoURL.setText("http://www.google.es");
        campoURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlIntroducida(evt);
            }
        });

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane1.setViewportView(salida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(campoURL, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urlIntroducida(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlIntroducida
        leerHTML(campoURL.getText());
    }//GEN-LAST:event_urlIntroducida

    public void leerHTML(String cadenaURL) {
        URL url = null;
        try {
            // Creamos una URL a partir del texto introducido
            url = new URL(cadenaURL);
        } catch (MalformedURLException e) {
            salida.setText("URL incorrecta");
            return;
        }
        salida.setText("");
        BufferedReader entrada = null;
        try {
            // Obtenemos una secuencia de entrada de caracteres para leer
            // la respuesta del servidor
            entrada = new BufferedReader(new InputStreamReader(url.openStream()));
        } catch (IOException e) {
            salida.setText("Error al abrir " + url.getHost());
        }
        String linea;
        try {
            // Mientras el servidor mantenga la conexion abierta..
            while ((linea = entrada.readLine()) !=null)
                salida.append(linea + "\n");
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
        try {
            // cerramos la secuencia de entrada
            entrada.close();
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarHTML().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoURL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea salida;
    // End of variables declaration//GEN-END:variables

}
