
/*
 * FileClient.java
 *
 * Created on 07-mar-2011, 22:54:00
 */

package fileserver;

import javax.swing.*;
import java.io.*;
import java.net.*;

/**
 *
 * @author jose
 */
public class FileClient extends javax.swing.JFrame {

    /** Creates new form FileClient */
    public FileClient() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoServidor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoFichero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Servidor:");

        campoServidor.setText("localhost");

        jLabel2.setText("Fichero Remoto:");

        jButton1.setText("Descargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descargarFichero(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoFichero)
                            .addComponent(campoServidor, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descargarFichero(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descargarFichero
        JFileChooser dialogoFichero = new JFileChooser();
        if (dialogoFichero.showSaveDialog(this)==JFileChooser.APPROVE_OPTION) {
            File fichero = dialogoFichero.getSelectedFile();
            Socket conexion;
            try {
                conexion = new Socket(campoServidor.getText(),2222);
            } catch (UnknownHostException e) {
                JOptionPane.showMessageDialog(this, "No se ha podido encontrar el host", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "No se ha podido establecer la conexión con el host", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            PrintWriter salida;
            InputStream entrada;
            FileOutputStream salidaFichero;
            try {
                salida = new PrintWriter(new OutputStreamWriter(conexion.getOutputStream()),true);
                entrada = conexion.getInputStream();
                salidaFichero = new FileOutputStream(fichero);
                int dato;
                System.out.println("Descargando " +campoFichero.getText());
                // Enviamos al servidor la ruta del fichero a descargar
                salida.println(campoFichero.getText());
                // Leemos el contenido binario enviado por el servidor
                while ((dato=entrada.read())!=-1)
                    salidaFichero.write(dato);
                salidaFichero.close();
                salida.close();
                entrada.close();
                conexion.close();
                JOptionPane.showMessageDialog(this, "Se ha completado la descarga", "Descarga completa", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error de Entrada/Salida: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_descargarFichero

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoFichero;
    private javax.swing.JTextField campoServidor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
